// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityEditV2rayConfigBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final AppBarLayout appBar;

  @NonNull
  public final TextInputEditText editAddress;

  @NonNull
  public final TextInputEditText editAlterId;

  @NonNull
  public final TextInputEditText editGrpcAuthority;

  @NonNull
  public final TextInputEditText editGrpcServiceName;

  @NonNull
  public final TextInputEditText editHost;

  @NonNull
  public final TextInputEditText editId;

  @NonNull
  public final TextInputEditText editKcpSeed;

  @NonNull
  public final TextInputEditText editPath;

  @NonNull
  public final TextInputEditText editPort;

  @NonNull
  public final TextInputEditText editPublicKey;

  @NonNull
  public final TextInputEditText editRemarks;

  @NonNull
  public final TextInputEditText editShortId;

  @NonNull
  public final TextInputEditText editSni;

  @NonNull
  public final TextInputEditText editSpiderX;

  @NonNull
  public final TextInputEditText editXhttpExtra;

  @NonNull
  public final Spinner spinnerAllowInsecure;

  @NonNull
  public final Spinner spinnerAlpn;

  @NonNull
  public final Spinner spinnerFp;

  @NonNull
  public final Spinner spinnerGrpcMode;

  @NonNull
  public final Spinner spinnerHeaderType;

  @NonNull
  public final Spinner spinnerNetwork;

  @NonNull
  public final Spinner spinnerSecurity;

  @NonNull
  public final Spinner spinnerTls;

  @NonNull
  public final Spinner spinnerXhttpMode;

  @NonNull
  public final TextInputLayout tilAddress;

  @NonNull
  public final LinearLayout tilAllowInsecure;

  @NonNull
  public final LinearLayout tilAlpn;

  @NonNull
  public final TextInputLayout tilAlterId;

  @NonNull
  public final LinearLayout tilFp;

  @NonNull
  public final TextInputLayout tilGrpcAuthority;

  @NonNull
  public final LinearLayout tilGrpcMode;

  @NonNull
  public final TextInputLayout tilGrpcServiceName;

  @NonNull
  public final LinearLayout tilHeaderType;

  @NonNull
  public final TextInputLayout tilHost;

  @NonNull
  public final TextInputLayout tilId;

  @NonNull
  public final TextInputLayout tilKcpSeed;

  @NonNull
  public final LinearLayout tilNetwork;

  @NonNull
  public final TextInputLayout tilPath;

  @NonNull
  public final TextInputLayout tilPort;

  @NonNull
  public final TextInputLayout tilPublicKey;

  @NonNull
  public final TextInputLayout tilRemarks;

  @NonNull
  public final LinearLayout tilSecurity;

  @NonNull
  public final TextInputLayout tilShortId;

  @NonNull
  public final TextInputLayout tilSni;

  @NonNull
  public final TextInputLayout tilSpiderX;

  @NonNull
  public final LinearLayout tilTls;

  @NonNull
  public final TextInputLayout tilXhttpExtra;

  @NonNull
  public final LinearLayout tilXhttpMode;

  @NonNull
  public final MaterialToolbar toolbar;

  @NonNull
  public final TextView tvAllowInsecure;

  @NonNull
  public final TextView tvAlpn;

  @NonNull
  public final TextView tvFp;

  @NonNull
  public final TextView tvGrpcMode;

  @NonNull
  public final TextView tvHeaderType;

  @NonNull
  public final TextView tvNetwork;

  @NonNull
  public final TextView tvSecurity;

  @NonNull
  public final TextView tvTls;

  @NonNull
  public final TextView tvXhttpMode;

  private ActivityEditV2rayConfigBinding(@NonNull CoordinatorLayout rootView,
      @NonNull AppBarLayout appBar, @NonNull TextInputEditText editAddress,
      @NonNull TextInputEditText editAlterId, @NonNull TextInputEditText editGrpcAuthority,
      @NonNull TextInputEditText editGrpcServiceName, @NonNull TextInputEditText editHost,
      @NonNull TextInputEditText editId, @NonNull TextInputEditText editKcpSeed,
      @NonNull TextInputEditText editPath, @NonNull TextInputEditText editPort,
      @NonNull TextInputEditText editPublicKey, @NonNull TextInputEditText editRemarks,
      @NonNull TextInputEditText editShortId, @NonNull TextInputEditText editSni,
      @NonNull TextInputEditText editSpiderX, @NonNull TextInputEditText editXhttpExtra,
      @NonNull Spinner spinnerAllowInsecure, @NonNull Spinner spinnerAlpn,
      @NonNull Spinner spinnerFp, @NonNull Spinner spinnerGrpcMode,
      @NonNull Spinner spinnerHeaderType, @NonNull Spinner spinnerNetwork,
      @NonNull Spinner spinnerSecurity, @NonNull Spinner spinnerTls,
      @NonNull Spinner spinnerXhttpMode, @NonNull TextInputLayout tilAddress,
      @NonNull LinearLayout tilAllowInsecure, @NonNull LinearLayout tilAlpn,
      @NonNull TextInputLayout tilAlterId, @NonNull LinearLayout tilFp,
      @NonNull TextInputLayout tilGrpcAuthority, @NonNull LinearLayout tilGrpcMode,
      @NonNull TextInputLayout tilGrpcServiceName, @NonNull LinearLayout tilHeaderType,
      @NonNull TextInputLayout tilHost, @NonNull TextInputLayout tilId,
      @NonNull TextInputLayout tilKcpSeed, @NonNull LinearLayout tilNetwork,
      @NonNull TextInputLayout tilPath, @NonNull TextInputLayout tilPort,
      @NonNull TextInputLayout tilPublicKey, @NonNull TextInputLayout tilRemarks,
      @NonNull LinearLayout tilSecurity, @NonNull TextInputLayout tilShortId,
      @NonNull TextInputLayout tilSni, @NonNull TextInputLayout tilSpiderX,
      @NonNull LinearLayout tilTls, @NonNull TextInputLayout tilXhttpExtra,
      @NonNull LinearLayout tilXhttpMode, @NonNull MaterialToolbar toolbar,
      @NonNull TextView tvAllowInsecure, @NonNull TextView tvAlpn, @NonNull TextView tvFp,
      @NonNull TextView tvGrpcMode, @NonNull TextView tvHeaderType, @NonNull TextView tvNetwork,
      @NonNull TextView tvSecurity, @NonNull TextView tvTls, @NonNull TextView tvXhttpMode) {
    this.rootView = rootView;
    this.appBar = appBar;
    this.editAddress = editAddress;
    this.editAlterId = editAlterId;
    this.editGrpcAuthority = editGrpcAuthority;
    this.editGrpcServiceName = editGrpcServiceName;
    this.editHost = editHost;
    this.editId = editId;
    this.editKcpSeed = editKcpSeed;
    this.editPath = editPath;
    this.editPort = editPort;
    this.editPublicKey = editPublicKey;
    this.editRemarks = editRemarks;
    this.editShortId = editShortId;
    this.editSni = editSni;
    this.editSpiderX = editSpiderX;
    this.editXhttpExtra = editXhttpExtra;
    this.spinnerAllowInsecure = spinnerAllowInsecure;
    this.spinnerAlpn = spinnerAlpn;
    this.spinnerFp = spinnerFp;
    this.spinnerGrpcMode = spinnerGrpcMode;
    this.spinnerHeaderType = spinnerHeaderType;
    this.spinnerNetwork = spinnerNetwork;
    this.spinnerSecurity = spinnerSecurity;
    this.spinnerTls = spinnerTls;
    this.spinnerXhttpMode = spinnerXhttpMode;
    this.tilAddress = tilAddress;
    this.tilAllowInsecure = tilAllowInsecure;
    this.tilAlpn = tilAlpn;
    this.tilAlterId = tilAlterId;
    this.tilFp = tilFp;
    this.tilGrpcAuthority = tilGrpcAuthority;
    this.tilGrpcMode = tilGrpcMode;
    this.tilGrpcServiceName = tilGrpcServiceName;
    this.tilHeaderType = tilHeaderType;
    this.tilHost = tilHost;
    this.tilId = tilId;
    this.tilKcpSeed = tilKcpSeed;
    this.tilNetwork = tilNetwork;
    this.tilPath = tilPath;
    this.tilPort = tilPort;
    this.tilPublicKey = tilPublicKey;
    this.tilRemarks = tilRemarks;
    this.tilSecurity = tilSecurity;
    this.tilShortId = tilShortId;
    this.tilSni = tilSni;
    this.tilSpiderX = tilSpiderX;
    this.tilTls = tilTls;
    this.tilXhttpExtra = tilXhttpExtra;
    this.tilXhttpMode = tilXhttpMode;
    this.toolbar = toolbar;
    this.tvAllowInsecure = tvAllowInsecure;
    this.tvAlpn = tvAlpn;
    this.tvFp = tvFp;
    this.tvGrpcMode = tvGrpcMode;
    this.tvHeaderType = tvHeaderType;
    this.tvNetwork = tvNetwork;
    this.tvSecurity = tvSecurity;
    this.tvTls = tvTls;
    this.tvXhttpMode = tvXhttpMode;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityEditV2rayConfigBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityEditV2rayConfigBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_edit_v2ray_config, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityEditV2rayConfigBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.appBar;
      AppBarLayout appBar = ViewBindings.findChildViewById(rootView, id);
      if (appBar == null) {
        break missingId;
      }

      id = R.id.edit_address;
      TextInputEditText editAddress = ViewBindings.findChildViewById(rootView, id);
      if (editAddress == null) {
        break missingId;
      }

      id = R.id.edit_alter_id;
      TextInputEditText editAlterId = ViewBindings.findChildViewById(rootView, id);
      if (editAlterId == null) {
        break missingId;
      }

      id = R.id.edit_grpc_authority;
      TextInputEditText editGrpcAuthority = ViewBindings.findChildViewById(rootView, id);
      if (editGrpcAuthority == null) {
        break missingId;
      }

      id = R.id.edit_grpc_service_name;
      TextInputEditText editGrpcServiceName = ViewBindings.findChildViewById(rootView, id);
      if (editGrpcServiceName == null) {
        break missingId;
      }

      id = R.id.edit_host;
      TextInputEditText editHost = ViewBindings.findChildViewById(rootView, id);
      if (editHost == null) {
        break missingId;
      }

      id = R.id.edit_id;
      TextInputEditText editId = ViewBindings.findChildViewById(rootView, id);
      if (editId == null) {
        break missingId;
      }

      id = R.id.edit_kcp_seed;
      TextInputEditText editKcpSeed = ViewBindings.findChildViewById(rootView, id);
      if (editKcpSeed == null) {
        break missingId;
      }

      id = R.id.edit_path;
      TextInputEditText editPath = ViewBindings.findChildViewById(rootView, id);
      if (editPath == null) {
        break missingId;
      }

      id = R.id.edit_port;
      TextInputEditText editPort = ViewBindings.findChildViewById(rootView, id);
      if (editPort == null) {
        break missingId;
      }

      id = R.id.edit_public_key;
      TextInputEditText editPublicKey = ViewBindings.findChildViewById(rootView, id);
      if (editPublicKey == null) {
        break missingId;
      }

      id = R.id.edit_remarks;
      TextInputEditText editRemarks = ViewBindings.findChildViewById(rootView, id);
      if (editRemarks == null) {
        break missingId;
      }

      id = R.id.edit_short_id;
      TextInputEditText editShortId = ViewBindings.findChildViewById(rootView, id);
      if (editShortId == null) {
        break missingId;
      }

      id = R.id.edit_sni;
      TextInputEditText editSni = ViewBindings.findChildViewById(rootView, id);
      if (editSni == null) {
        break missingId;
      }

      id = R.id.edit_spider_x;
      TextInputEditText editSpiderX = ViewBindings.findChildViewById(rootView, id);
      if (editSpiderX == null) {
        break missingId;
      }

      id = R.id.edit_xhttp_extra;
      TextInputEditText editXhttpExtra = ViewBindings.findChildViewById(rootView, id);
      if (editXhttpExtra == null) {
        break missingId;
      }

      id = R.id.spinner_allow_insecure;
      Spinner spinnerAllowInsecure = ViewBindings.findChildViewById(rootView, id);
      if (spinnerAllowInsecure == null) {
        break missingId;
      }

      id = R.id.spinner_alpn;
      Spinner spinnerAlpn = ViewBindings.findChildViewById(rootView, id);
      if (spinnerAlpn == null) {
        break missingId;
      }

      id = R.id.spinner_fp;
      Spinner spinnerFp = ViewBindings.findChildViewById(rootView, id);
      if (spinnerFp == null) {
        break missingId;
      }

      id = R.id.spinner_grpc_mode;
      Spinner spinnerGrpcMode = ViewBindings.findChildViewById(rootView, id);
      if (spinnerGrpcMode == null) {
        break missingId;
      }

      id = R.id.spinner_header_type;
      Spinner spinnerHeaderType = ViewBindings.findChildViewById(rootView, id);
      if (spinnerHeaderType == null) {
        break missingId;
      }

      id = R.id.spinner_network;
      Spinner spinnerNetwork = ViewBindings.findChildViewById(rootView, id);
      if (spinnerNetwork == null) {
        break missingId;
      }

      id = R.id.spinner_security;
      Spinner spinnerSecurity = ViewBindings.findChildViewById(rootView, id);
      if (spinnerSecurity == null) {
        break missingId;
      }

      id = R.id.spinner_tls;
      Spinner spinnerTls = ViewBindings.findChildViewById(rootView, id);
      if (spinnerTls == null) {
        break missingId;
      }

      id = R.id.spinner_xhttp_mode;
      Spinner spinnerXhttpMode = ViewBindings.findChildViewById(rootView, id);
      if (spinnerXhttpMode == null) {
        break missingId;
      }

      id = R.id.til_address;
      TextInputLayout tilAddress = ViewBindings.findChildViewById(rootView, id);
      if (tilAddress == null) {
        break missingId;
      }

      id = R.id.til_allow_insecure;
      LinearLayout tilAllowInsecure = ViewBindings.findChildViewById(rootView, id);
      if (tilAllowInsecure == null) {
        break missingId;
      }

      id = R.id.til_alpn;
      LinearLayout tilAlpn = ViewBindings.findChildViewById(rootView, id);
      if (tilAlpn == null) {
        break missingId;
      }

      id = R.id.til_alter_id;
      TextInputLayout tilAlterId = ViewBindings.findChildViewById(rootView, id);
      if (tilAlterId == null) {
        break missingId;
      }

      id = R.id.til_fp;
      LinearLayout tilFp = ViewBindings.findChildViewById(rootView, id);
      if (tilFp == null) {
        break missingId;
      }

      id = R.id.til_grpc_authority;
      TextInputLayout tilGrpcAuthority = ViewBindings.findChildViewById(rootView, id);
      if (tilGrpcAuthority == null) {
        break missingId;
      }

      id = R.id.til_grpc_mode;
      LinearLayout tilGrpcMode = ViewBindings.findChildViewById(rootView, id);
      if (tilGrpcMode == null) {
        break missingId;
      }

      id = R.id.til_grpc_service_name;
      TextInputLayout tilGrpcServiceName = ViewBindings.findChildViewById(rootView, id);
      if (tilGrpcServiceName == null) {
        break missingId;
      }

      id = R.id.til_header_type;
      LinearLayout tilHeaderType = ViewBindings.findChildViewById(rootView, id);
      if (tilHeaderType == null) {
        break missingId;
      }

      id = R.id.til_host;
      TextInputLayout tilHost = ViewBindings.findChildViewById(rootView, id);
      if (tilHost == null) {
        break missingId;
      }

      id = R.id.til_id;
      TextInputLayout tilId = ViewBindings.findChildViewById(rootView, id);
      if (tilId == null) {
        break missingId;
      }

      id = R.id.til_kcp_seed;
      TextInputLayout tilKcpSeed = ViewBindings.findChildViewById(rootView, id);
      if (tilKcpSeed == null) {
        break missingId;
      }

      id = R.id.til_network;
      LinearLayout tilNetwork = ViewBindings.findChildViewById(rootView, id);
      if (tilNetwork == null) {
        break missingId;
      }

      id = R.id.til_path;
      TextInputLayout tilPath = ViewBindings.findChildViewById(rootView, id);
      if (tilPath == null) {
        break missingId;
      }

      id = R.id.til_port;
      TextInputLayout tilPort = ViewBindings.findChildViewById(rootView, id);
      if (tilPort == null) {
        break missingId;
      }

      id = R.id.til_public_key;
      TextInputLayout tilPublicKey = ViewBindings.findChildViewById(rootView, id);
      if (tilPublicKey == null) {
        break missingId;
      }

      id = R.id.til_remarks;
      TextInputLayout tilRemarks = ViewBindings.findChildViewById(rootView, id);
      if (tilRemarks == null) {
        break missingId;
      }

      id = R.id.til_security;
      LinearLayout tilSecurity = ViewBindings.findChildViewById(rootView, id);
      if (tilSecurity == null) {
        break missingId;
      }

      id = R.id.til_short_id;
      TextInputLayout tilShortId = ViewBindings.findChildViewById(rootView, id);
      if (tilShortId == null) {
        break missingId;
      }

      id = R.id.til_sni;
      TextInputLayout tilSni = ViewBindings.findChildViewById(rootView, id);
      if (tilSni == null) {
        break missingId;
      }

      id = R.id.til_spider_x;
      TextInputLayout tilSpiderX = ViewBindings.findChildViewById(rootView, id);
      if (tilSpiderX == null) {
        break missingId;
      }

      id = R.id.til_tls;
      LinearLayout tilTls = ViewBindings.findChildViewById(rootView, id);
      if (tilTls == null) {
        break missingId;
      }

      id = R.id.til_xhttp_extra;
      TextInputLayout tilXhttpExtra = ViewBindings.findChildViewById(rootView, id);
      if (tilXhttpExtra == null) {
        break missingId;
      }

      id = R.id.til_xhttp_mode;
      LinearLayout tilXhttpMode = ViewBindings.findChildViewById(rootView, id);
      if (tilXhttpMode == null) {
        break missingId;
      }

      id = R.id.toolbar;
      MaterialToolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      id = R.id.tv_allow_insecure;
      TextView tvAllowInsecure = ViewBindings.findChildViewById(rootView, id);
      if (tvAllowInsecure == null) {
        break missingId;
      }

      id = R.id.tv_alpn;
      TextView tvAlpn = ViewBindings.findChildViewById(rootView, id);
      if (tvAlpn == null) {
        break missingId;
      }

      id = R.id.tv_fp;
      TextView tvFp = ViewBindings.findChildViewById(rootView, id);
      if (tvFp == null) {
        break missingId;
      }

      id = R.id.tv_grpc_mode;
      TextView tvGrpcMode = ViewBindings.findChildViewById(rootView, id);
      if (tvGrpcMode == null) {
        break missingId;
      }

      id = R.id.tv_header_type;
      TextView tvHeaderType = ViewBindings.findChildViewById(rootView, id);
      if (tvHeaderType == null) {
        break missingId;
      }

      id = R.id.tv_network;
      TextView tvNetwork = ViewBindings.findChildViewById(rootView, id);
      if (tvNetwork == null) {
        break missingId;
      }

      id = R.id.tv_security;
      TextView tvSecurity = ViewBindings.findChildViewById(rootView, id);
      if (tvSecurity == null) {
        break missingId;
      }

      id = R.id.tv_tls;
      TextView tvTls = ViewBindings.findChildViewById(rootView, id);
      if (tvTls == null) {
        break missingId;
      }

      id = R.id.tv_xhttp_mode;
      TextView tvXhttpMode = ViewBindings.findChildViewById(rootView, id);
      if (tvXhttpMode == null) {
        break missingId;
      }

      return new ActivityEditV2rayConfigBinding((CoordinatorLayout) rootView, appBar, editAddress,
          editAlterId, editGrpcAuthority, editGrpcServiceName, editHost, editId, editKcpSeed,
          editPath, editPort, editPublicKey, editRemarks, editShortId, editSni, editSpiderX,
          editXhttpExtra, spinnerAllowInsecure, spinnerAlpn, spinnerFp, spinnerGrpcMode,
          spinnerHeaderType, spinnerNetwork, spinnerSecurity, spinnerTls, spinnerXhttpMode,
          tilAddress, tilAllowInsecure, tilAlpn, tilAlterId, tilFp, tilGrpcAuthority, tilGrpcMode,
          tilGrpcServiceName, tilHeaderType, tilHost, tilId, tilKcpSeed, tilNetwork, tilPath,
          tilPort, tilPublicKey, tilRemarks, tilSecurity, tilShortId, tilSni, tilSpiderX, tilTls,
          tilXhttpExtra, tilXhttpMode, toolbar, tvAllowInsecure, tvAlpn, tvFp, tvGrpcMode,
          tvHeaderType, tvNetwork, tvSecurity, tvTls, tvXhttpMode);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
