// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityHcBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView Txthost1;

  @NonNull
  public final TextView Txthost2;

  @NonNull
  public final Button buttonSearch;

  @NonNull
  public final CheckBox checkBoxDirectRequest;

  @NonNull
  public final TextView dt;

  @NonNull
  public final EditText editTextProxy;

  @NonNull
  public final EditText editTextUrl;

  @NonNull
  public final ListView listLogs;

  @NonNull
  public final LinearLayout mainV;

  @NonNull
  public final Spinner spinnerRequestMethod;

  @NonNull
  public final Toolbar toolbarMain;

  private ActivityHcBinding(@NonNull LinearLayout rootView, @NonNull TextView Txthost1,
      @NonNull TextView Txthost2, @NonNull Button buttonSearch,
      @NonNull CheckBox checkBoxDirectRequest, @NonNull TextView dt,
      @NonNull EditText editTextProxy, @NonNull EditText editTextUrl, @NonNull ListView listLogs,
      @NonNull LinearLayout mainV, @NonNull Spinner spinnerRequestMethod,
      @NonNull Toolbar toolbarMain) {
    this.rootView = rootView;
    this.Txthost1 = Txthost1;
    this.Txthost2 = Txthost2;
    this.buttonSearch = buttonSearch;
    this.checkBoxDirectRequest = checkBoxDirectRequest;
    this.dt = dt;
    this.editTextProxy = editTextProxy;
    this.editTextUrl = editTextUrl;
    this.listLogs = listLogs;
    this.mainV = mainV;
    this.spinnerRequestMethod = spinnerRequestMethod;
    this.toolbarMain = toolbarMain;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityHcBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityHcBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_hc, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityHcBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.Txthost1;
      TextView Txthost1 = ViewBindings.findChildViewById(rootView, id);
      if (Txthost1 == null) {
        break missingId;
      }

      id = R.id.Txthost2;
      TextView Txthost2 = ViewBindings.findChildViewById(rootView, id);
      if (Txthost2 == null) {
        break missingId;
      }

      id = R.id.buttonSearch;
      Button buttonSearch = ViewBindings.findChildViewById(rootView, id);
      if (buttonSearch == null) {
        break missingId;
      }

      id = R.id.checkBoxDirectRequest;
      CheckBox checkBoxDirectRequest = ViewBindings.findChildViewById(rootView, id);
      if (checkBoxDirectRequest == null) {
        break missingId;
      }

      id = R.id.dt;
      TextView dt = ViewBindings.findChildViewById(rootView, id);
      if (dt == null) {
        break missingId;
      }

      id = R.id.editTextProxy;
      EditText editTextProxy = ViewBindings.findChildViewById(rootView, id);
      if (editTextProxy == null) {
        break missingId;
      }

      id = R.id.editTextUrl;
      EditText editTextUrl = ViewBindings.findChildViewById(rootView, id);
      if (editTextUrl == null) {
        break missingId;
      }

      id = R.id.listLogs;
      ListView listLogs = ViewBindings.findChildViewById(rootView, id);
      if (listLogs == null) {
        break missingId;
      }

      id = R.id.mainV;
      LinearLayout mainV = ViewBindings.findChildViewById(rootView, id);
      if (mainV == null) {
        break missingId;
      }

      id = R.id.spinnerRequestMethod;
      Spinner spinnerRequestMethod = ViewBindings.findChildViewById(rootView, id);
      if (spinnerRequestMethod == null) {
        break missingId;
      }

      id = R.id.toolbar_main;
      Toolbar toolbarMain = ViewBindings.findChildViewById(rootView, id);
      if (toolbarMain == null) {
        break missingId;
      }

      return new ActivityHcBinding((LinearLayout) rootView, Txthost1, Txthost2, buttonSearch,
          checkBoxDirectRequest, dt, editTextProxy, editTextUrl, listLogs, mainV,
          spinnerRequestMethod, toolbarMain);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
