// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.gms.ads.AdView;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityAboutBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final AdView adView2;

  @NonNull
  public final TextView appVersion;

  @NonNull
  public final LinearLayout changelog;

  @NonNull
  public final LinearLayout credits;

  @NonNull
  public final LinearLayout developer;

  @NonNull
  public final LinearLayout developerpv;

  @NonNull
  public final LinearLayout license;

  private ActivityAboutBinding(@NonNull LinearLayout rootView, @NonNull AdView adView2,
      @NonNull TextView appVersion, @NonNull LinearLayout changelog, @NonNull LinearLayout credits,
      @NonNull LinearLayout developer, @NonNull LinearLayout developerpv,
      @NonNull LinearLayout license) {
    this.rootView = rootView;
    this.adView2 = adView2;
    this.appVersion = appVersion;
    this.changelog = changelog;
    this.credits = credits;
    this.developer = developer;
    this.developerpv = developerpv;
    this.license = license;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityAboutBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityAboutBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_about, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityAboutBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.adView2;
      AdView adView2 = ViewBindings.findChildViewById(rootView, id);
      if (adView2 == null) {
        break missingId;
      }

      id = R.id.appVersion;
      TextView appVersion = ViewBindings.findChildViewById(rootView, id);
      if (appVersion == null) {
        break missingId;
      }

      id = R.id.changelog;
      LinearLayout changelog = ViewBindings.findChildViewById(rootView, id);
      if (changelog == null) {
        break missingId;
      }

      id = R.id.credits;
      LinearLayout credits = ViewBindings.findChildViewById(rootView, id);
      if (credits == null) {
        break missingId;
      }

      id = R.id.developer;
      LinearLayout developer = ViewBindings.findChildViewById(rootView, id);
      if (developer == null) {
        break missingId;
      }

      id = R.id.developerpv;
      LinearLayout developerpv = ViewBindings.findChildViewById(rootView, id);
      if (developerpv == null) {
        break missingId;
      }

      id = R.id.license;
      LinearLayout license = ViewBindings.findChildViewById(rootView, id);
      if (license == null) {
        break missingId;
      }

      return new ActivityAboutBinding((LinearLayout) rootView, adView2, appVersion, changelog,
          credits, developer, developerpv, license);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
