// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.gms.ads.AdView;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final LinearLayout activityMainLinearLayout;

  @NonNull
  public final TextView activityMainMensagemConfigTextView;

  @NonNull
  public final AppCompatButton activityStarterButtonMain;

  @NonNull
  public final CardView activitymainCardView1;

  @NonNull
  public final TextView activitymainTextView1;

  @NonNull
  public final AdView adView1;

  @NonNull
  public final FrameLayout admobAdViewContainer;

  @NonNull
  public final FrameLayout admobNativeAdContainer;

  @NonNull
  public final CardView btnSelectImage;

  @NonNull
  public final CardView cardViewAds;

  @NonNull
  public final CardView cardViewNews;

  @NonNull
  public final CardView connectionCardView;

  @NonNull
  public final RelativeLayout controlMenuLayout;

  @NonNull
  public final LinearLayout httpObfsLayout;

  @NonNull
  public final ImageView imageServerLoad;

  @NonNull
  public final ImageView imageViewHttpObfs;

  @NonNull
  public final ImageView imageViewProxy;

  @NonNull
  public final ImageView imageViewSNI;

  @NonNull
  public final FloatingActionButton info;

  @NonNull
  public final TextInputLayout inputLayoutPayloadDefault;

  @NonNull
  public final TextView newsTitle;

  @NonNull
  public final TextInputLayout payload;

  @NonNull
  public final TextInputEditText payloadEdit;

  @NonNull
  public final LinearLayout proxyLayout;

  @NonNull
  public final TextView proxyText;

  @NonNull
  public final LinearLayout serverLayout;

  @NonNull
  public final LinearLayout sslLayout;

  @NonNull
  public final TextView sslText;

  @NonNull
  public final TextView textView;

  @NonNull
  public final TextView textViewHttpObfs;

  @NonNull
  public final TextView textViewHttpTitle;

  @NonNull
  public final TextView textViewServer;

  @NonNull
  public final TextView textViewSniTitle;

  @NonNull
  public final CardView tunnelCardView;

  private ActivityMainBinding(@NonNull RelativeLayout rootView,
      @NonNull LinearLayout activityMainLinearLayout,
      @NonNull TextView activityMainMensagemConfigTextView,
      @NonNull AppCompatButton activityStarterButtonMain, @NonNull CardView activitymainCardView1,
      @NonNull TextView activitymainTextView1, @NonNull AdView adView1,
      @NonNull FrameLayout admobAdViewContainer, @NonNull FrameLayout admobNativeAdContainer,
      @NonNull CardView btnSelectImage, @NonNull CardView cardViewAds,
      @NonNull CardView cardViewNews, @NonNull CardView connectionCardView,
      @NonNull RelativeLayout controlMenuLayout, @NonNull LinearLayout httpObfsLayout,
      @NonNull ImageView imageServerLoad, @NonNull ImageView imageViewHttpObfs,
      @NonNull ImageView imageViewProxy, @NonNull ImageView imageViewSNI,
      @NonNull FloatingActionButton info, @NonNull TextInputLayout inputLayoutPayloadDefault,
      @NonNull TextView newsTitle, @NonNull TextInputLayout payload,
      @NonNull TextInputEditText payloadEdit, @NonNull LinearLayout proxyLayout,
      @NonNull TextView proxyText, @NonNull LinearLayout serverLayout,
      @NonNull LinearLayout sslLayout, @NonNull TextView sslText, @NonNull TextView textView,
      @NonNull TextView textViewHttpObfs, @NonNull TextView textViewHttpTitle,
      @NonNull TextView textViewServer, @NonNull TextView textViewSniTitle,
      @NonNull CardView tunnelCardView) {
    this.rootView = rootView;
    this.activityMainLinearLayout = activityMainLinearLayout;
    this.activityMainMensagemConfigTextView = activityMainMensagemConfigTextView;
    this.activityStarterButtonMain = activityStarterButtonMain;
    this.activitymainCardView1 = activitymainCardView1;
    this.activitymainTextView1 = activitymainTextView1;
    this.adView1 = adView1;
    this.admobAdViewContainer = admobAdViewContainer;
    this.admobNativeAdContainer = admobNativeAdContainer;
    this.btnSelectImage = btnSelectImage;
    this.cardViewAds = cardViewAds;
    this.cardViewNews = cardViewNews;
    this.connectionCardView = connectionCardView;
    this.controlMenuLayout = controlMenuLayout;
    this.httpObfsLayout = httpObfsLayout;
    this.imageServerLoad = imageServerLoad;
    this.imageViewHttpObfs = imageViewHttpObfs;
    this.imageViewProxy = imageViewProxy;
    this.imageViewSNI = imageViewSNI;
    this.info = info;
    this.inputLayoutPayloadDefault = inputLayoutPayloadDefault;
    this.newsTitle = newsTitle;
    this.payload = payload;
    this.payloadEdit = payloadEdit;
    this.proxyLayout = proxyLayout;
    this.proxyText = proxyText;
    this.serverLayout = serverLayout;
    this.sslLayout = sslLayout;
    this.sslText = sslText;
    this.textView = textView;
    this.textViewHttpObfs = textViewHttpObfs;
    this.textViewHttpTitle = textViewHttpTitle;
    this.textViewServer = textViewServer;
    this.textViewSniTitle = textViewSniTitle;
    this.tunnelCardView = tunnelCardView;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.activity_mainLinearLayout;
      LinearLayout activityMainLinearLayout = ViewBindings.findChildViewById(rootView, id);
      if (activityMainLinearLayout == null) {
        break missingId;
      }

      id = R.id.activity_mainMensagemConfigTextView;
      TextView activityMainMensagemConfigTextView = ViewBindings.findChildViewById(rootView, id);
      if (activityMainMensagemConfigTextView == null) {
        break missingId;
      }

      id = R.id.activity_starterButtonMain;
      AppCompatButton activityStarterButtonMain = ViewBindings.findChildViewById(rootView, id);
      if (activityStarterButtonMain == null) {
        break missingId;
      }

      id = R.id.activitymainCardView1;
      CardView activitymainCardView1 = ViewBindings.findChildViewById(rootView, id);
      if (activitymainCardView1 == null) {
        break missingId;
      }

      id = R.id.activitymainTextView1;
      TextView activitymainTextView1 = ViewBindings.findChildViewById(rootView, id);
      if (activitymainTextView1 == null) {
        break missingId;
      }

      id = R.id.adView1;
      AdView adView1 = ViewBindings.findChildViewById(rootView, id);
      if (adView1 == null) {
        break missingId;
      }

      id = R.id.admobAdViewContainer;
      FrameLayout admobAdViewContainer = ViewBindings.findChildViewById(rootView, id);
      if (admobAdViewContainer == null) {
        break missingId;
      }

      id = R.id.admob_native_ad_container;
      FrameLayout admobNativeAdContainer = ViewBindings.findChildViewById(rootView, id);
      if (admobNativeAdContainer == null) {
        break missingId;
      }

      id = R.id.btnSelectImage;
      CardView btnSelectImage = ViewBindings.findChildViewById(rootView, id);
      if (btnSelectImage == null) {
        break missingId;
      }

      id = R.id.cardViewAds;
      CardView cardViewAds = ViewBindings.findChildViewById(rootView, id);
      if (cardViewAds == null) {
        break missingId;
      }

      id = R.id.cardViewNews;
      CardView cardViewNews = ViewBindings.findChildViewById(rootView, id);
      if (cardViewNews == null) {
        break missingId;
      }

      id = R.id.connection_cardView;
      CardView connectionCardView = ViewBindings.findChildViewById(rootView, id);
      if (connectionCardView == null) {
        break missingId;
      }

      id = R.id.controlMenuLayout;
      RelativeLayout controlMenuLayout = ViewBindings.findChildViewById(rootView, id);
      if (controlMenuLayout == null) {
        break missingId;
      }

      id = R.id.httpObfsLayout;
      LinearLayout httpObfsLayout = ViewBindings.findChildViewById(rootView, id);
      if (httpObfsLayout == null) {
        break missingId;
      }

      id = R.id.imageServerLoad;
      ImageView imageServerLoad = ViewBindings.findChildViewById(rootView, id);
      if (imageServerLoad == null) {
        break missingId;
      }

      id = R.id.imageViewHttpObfs;
      ImageView imageViewHttpObfs = ViewBindings.findChildViewById(rootView, id);
      if (imageViewHttpObfs == null) {
        break missingId;
      }

      id = R.id.imageViewProxy;
      ImageView imageViewProxy = ViewBindings.findChildViewById(rootView, id);
      if (imageViewProxy == null) {
        break missingId;
      }

      id = R.id.imageViewSNI;
      ImageView imageViewSNI = ViewBindings.findChildViewById(rootView, id);
      if (imageViewSNI == null) {
        break missingId;
      }

      id = R.id.info;
      FloatingActionButton info = ViewBindings.findChildViewById(rootView, id);
      if (info == null) {
        break missingId;
      }

      id = R.id.inputLayoutPayloadDefault;
      TextInputLayout inputLayoutPayloadDefault = ViewBindings.findChildViewById(rootView, id);
      if (inputLayoutPayloadDefault == null) {
        break missingId;
      }

      id = R.id.newsTitle;
      TextView newsTitle = ViewBindings.findChildViewById(rootView, id);
      if (newsTitle == null) {
        break missingId;
      }

      id = R.id.payload;
      TextInputLayout payload = ViewBindings.findChildViewById(rootView, id);
      if (payload == null) {
        break missingId;
      }

      id = R.id.payloadEdit;
      TextInputEditText payloadEdit = ViewBindings.findChildViewById(rootView, id);
      if (payloadEdit == null) {
        break missingId;
      }

      id = R.id.proxyLayout;
      LinearLayout proxyLayout = ViewBindings.findChildViewById(rootView, id);
      if (proxyLayout == null) {
        break missingId;
      }

      id = R.id.proxyText;
      TextView proxyText = ViewBindings.findChildViewById(rootView, id);
      if (proxyText == null) {
        break missingId;
      }

      id = R.id.serverLayout;
      LinearLayout serverLayout = ViewBindings.findChildViewById(rootView, id);
      if (serverLayout == null) {
        break missingId;
      }

      id = R.id.sslLayout;
      LinearLayout sslLayout = ViewBindings.findChildViewById(rootView, id);
      if (sslLayout == null) {
        break missingId;
      }

      id = R.id.sslText;
      TextView sslText = ViewBindings.findChildViewById(rootView, id);
      if (sslText == null) {
        break missingId;
      }

      id = R.id.textView;
      TextView textView = ViewBindings.findChildViewById(rootView, id);
      if (textView == null) {
        break missingId;
      }

      id = R.id.textViewHttpObfs;
      TextView textViewHttpObfs = ViewBindings.findChildViewById(rootView, id);
      if (textViewHttpObfs == null) {
        break missingId;
      }

      id = R.id.textViewHttpTitle;
      TextView textViewHttpTitle = ViewBindings.findChildViewById(rootView, id);
      if (textViewHttpTitle == null) {
        break missingId;
      }

      id = R.id.textViewServer;
      TextView textViewServer = ViewBindings.findChildViewById(rootView, id);
      if (textViewServer == null) {
        break missingId;
      }

      id = R.id.textViewSniTitle;
      TextView textViewSniTitle = ViewBindings.findChildViewById(rootView, id);
      if (textViewSniTitle == null) {
        break missingId;
      }

      id = R.id.tunnelCardView;
      CardView tunnelCardView = ViewBindings.findChildViewById(rootView, id);
      if (tunnelCardView == null) {
        break missingId;
      }

      return new ActivityMainBinding((RelativeLayout) rootView, activityMainLinearLayout,
          activityMainMensagemConfigTextView, activityStarterButtonMain, activitymainCardView1,
          activitymainTextView1, adView1, admobAdViewContainer, admobNativeAdContainer,
          btnSelectImage, cardViewAds, cardViewNews, connectionCardView, controlMenuLayout,
          httpObfsLayout, imageServerLoad, imageViewHttpObfs, imageViewProxy, imageViewSNI, info,
          inputLayoutPayloadDefault, newsTitle, payload, payloadEdit, proxyLayout, proxyText,
          serverLayout, sslLayout, sslText, textView, textViewHttpObfs, textViewHttpTitle,
          textViewServer, textViewSniTitle, tunnelCardView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
