// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.textfield.TextInputLayout;
import com.jepongdevxyz.vpn.R;
import host.stjin.expandablecardview.ExpandableCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityConfigExportBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final FloatingActionButton activityConfigExportButton;

  @NonNull
  public final TextInputLayout activityConfigExportLayoutMensagemEdit;

  @NonNull
  public final EditText activityConfigExportMensagemEdit;

  @NonNull
  public final EditText activityConfigExportNomeEdit;

  @NonNull
  public final CheckBox activityConfigExportProtegerCheck;

  @NonNull
  public final EditText activityConfigExportautoredit;

  @NonNull
  public final TextInputLayout activityConfigExportlayoutautor;

  @NonNull
  public final RelativeLayout adView;

  @NonNull
  public final AppBarLayout appbar;

  @NonNull
  public final CheckBox autorCheck;

  @NonNull
  public final LinearLayout cardOptions;

  @NonNull
  public final ExpandableCardView cardSecure;

  @NonNull
  public final EditText editpaa;

  @NonNull
  public final EditText hwidtext;

  @NonNull
  public final TextInputLayout inputlayouthwid;

  @NonNull
  public final LinearLayout layoutAutor;

  @NonNull
  public final LinearLayout layoutHwid;

  @NonNull
  public final LinearLayout layoutMsg;

  @NonNull
  public final LinearLayout main;

  @NonNull
  public final CoordinatorLayout mainView;

  @NonNull
  public final CheckBox msgCheck;

  @NonNull
  public final TextInputLayout passlauoy;

  @NonNull
  public final LinearLayout passo;

  @NonNull
  public final Toolbar toolbarMain;

  private ActivityConfigExportBinding(@NonNull CoordinatorLayout rootView,
      @NonNull FloatingActionButton activityConfigExportButton,
      @NonNull TextInputLayout activityConfigExportLayoutMensagemEdit,
      @NonNull EditText activityConfigExportMensagemEdit,
      @NonNull EditText activityConfigExportNomeEdit,
      @NonNull CheckBox activityConfigExportProtegerCheck,
      @NonNull EditText activityConfigExportautoredit,
      @NonNull TextInputLayout activityConfigExportlayoutautor, @NonNull RelativeLayout adView,
      @NonNull AppBarLayout appbar, @NonNull CheckBox autorCheck, @NonNull LinearLayout cardOptions,
      @NonNull ExpandableCardView cardSecure, @NonNull EditText editpaa, @NonNull EditText hwidtext,
      @NonNull TextInputLayout inputlayouthwid, @NonNull LinearLayout layoutAutor,
      @NonNull LinearLayout layoutHwid, @NonNull LinearLayout layoutMsg, @NonNull LinearLayout main,
      @NonNull CoordinatorLayout mainView, @NonNull CheckBox msgCheck,
      @NonNull TextInputLayout passlauoy, @NonNull LinearLayout passo,
      @NonNull Toolbar toolbarMain) {
    this.rootView = rootView;
    this.activityConfigExportButton = activityConfigExportButton;
    this.activityConfigExportLayoutMensagemEdit = activityConfigExportLayoutMensagemEdit;
    this.activityConfigExportMensagemEdit = activityConfigExportMensagemEdit;
    this.activityConfigExportNomeEdit = activityConfigExportNomeEdit;
    this.activityConfigExportProtegerCheck = activityConfigExportProtegerCheck;
    this.activityConfigExportautoredit = activityConfigExportautoredit;
    this.activityConfigExportlayoutautor = activityConfigExportlayoutautor;
    this.adView = adView;
    this.appbar = appbar;
    this.autorCheck = autorCheck;
    this.cardOptions = cardOptions;
    this.cardSecure = cardSecure;
    this.editpaa = editpaa;
    this.hwidtext = hwidtext;
    this.inputlayouthwid = inputlayouthwid;
    this.layoutAutor = layoutAutor;
    this.layoutHwid = layoutHwid;
    this.layoutMsg = layoutMsg;
    this.main = main;
    this.mainView = mainView;
    this.msgCheck = msgCheck;
    this.passlauoy = passlauoy;
    this.passo = passo;
    this.toolbarMain = toolbarMain;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityConfigExportBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityConfigExportBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_config_export, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityConfigExportBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.activity_config_exportButton;
      FloatingActionButton activityConfigExportButton = ViewBindings.findChildViewById(rootView, id);
      if (activityConfigExportButton == null) {
        break missingId;
      }

      id = R.id.activity_config_exportLayoutMensagemEdit;
      TextInputLayout activityConfigExportLayoutMensagemEdit = ViewBindings.findChildViewById(rootView, id);
      if (activityConfigExportLayoutMensagemEdit == null) {
        break missingId;
      }

      id = R.id.activity_config_exportMensagemEdit;
      EditText activityConfigExportMensagemEdit = ViewBindings.findChildViewById(rootView, id);
      if (activityConfigExportMensagemEdit == null) {
        break missingId;
      }

      id = R.id.activity_config_exportNomeEdit;
      EditText activityConfigExportNomeEdit = ViewBindings.findChildViewById(rootView, id);
      if (activityConfigExportNomeEdit == null) {
        break missingId;
      }

      id = R.id.activity_config_exportProtegerCheck;
      CheckBox activityConfigExportProtegerCheck = ViewBindings.findChildViewById(rootView, id);
      if (activityConfigExportProtegerCheck == null) {
        break missingId;
      }

      id = R.id.activity_config_exportautoredit;
      EditText activityConfigExportautoredit = ViewBindings.findChildViewById(rootView, id);
      if (activityConfigExportautoredit == null) {
        break missingId;
      }

      id = R.id.activity_config_exportlayoutautor;
      TextInputLayout activityConfigExportlayoutautor = ViewBindings.findChildViewById(rootView, id);
      if (activityConfigExportlayoutautor == null) {
        break missingId;
      }

      id = R.id.adView;
      RelativeLayout adView = ViewBindings.findChildViewById(rootView, id);
      if (adView == null) {
        break missingId;
      }

      id = R.id.appbar;
      AppBarLayout appbar = ViewBindings.findChildViewById(rootView, id);
      if (appbar == null) {
        break missingId;
      }

      id = R.id.autor_check;
      CheckBox autorCheck = ViewBindings.findChildViewById(rootView, id);
      if (autorCheck == null) {
        break missingId;
      }

      id = R.id.card_options;
      LinearLayout cardOptions = ViewBindings.findChildViewById(rootView, id);
      if (cardOptions == null) {
        break missingId;
      }

      id = R.id.card_secure;
      ExpandableCardView cardSecure = ViewBindings.findChildViewById(rootView, id);
      if (cardSecure == null) {
        break missingId;
      }

      id = R.id.editpaa;
      EditText editpaa = ViewBindings.findChildViewById(rootView, id);
      if (editpaa == null) {
        break missingId;
      }

      id = R.id.hwidtext;
      EditText hwidtext = ViewBindings.findChildViewById(rootView, id);
      if (hwidtext == null) {
        break missingId;
      }

      id = R.id.inputlayouthwid;
      TextInputLayout inputlayouthwid = ViewBindings.findChildViewById(rootView, id);
      if (inputlayouthwid == null) {
        break missingId;
      }

      id = R.id.layout_autor;
      LinearLayout layoutAutor = ViewBindings.findChildViewById(rootView, id);
      if (layoutAutor == null) {
        break missingId;
      }

      id = R.id.layout_hwid;
      LinearLayout layoutHwid = ViewBindings.findChildViewById(rootView, id);
      if (layoutHwid == null) {
        break missingId;
      }

      id = R.id.layout_msg;
      LinearLayout layoutMsg = ViewBindings.findChildViewById(rootView, id);
      if (layoutMsg == null) {
        break missingId;
      }

      id = R.id.main;
      LinearLayout main = ViewBindings.findChildViewById(rootView, id);
      if (main == null) {
        break missingId;
      }

      CoordinatorLayout mainView = (CoordinatorLayout) rootView;

      id = R.id.msg_check;
      CheckBox msgCheck = ViewBindings.findChildViewById(rootView, id);
      if (msgCheck == null) {
        break missingId;
      }

      id = R.id.passlauoy;
      TextInputLayout passlauoy = ViewBindings.findChildViewById(rootView, id);
      if (passlauoy == null) {
        break missingId;
      }

      id = R.id.passo;
      LinearLayout passo = ViewBindings.findChildViewById(rootView, id);
      if (passo == null) {
        break missingId;
      }

      id = R.id.toolbar_main;
      Toolbar toolbarMain = ViewBindings.findChildViewById(rootView, id);
      if (toolbarMain == null) {
        break missingId;
      }

      return new ActivityConfigExportBinding((CoordinatorLayout) rootView,
          activityConfigExportButton, activityConfigExportLayoutMensagemEdit,
          activityConfigExportMensagemEdit, activityConfigExportNomeEdit,
          activityConfigExportProtegerCheck, activityConfigExportautoredit,
          activityConfigExportlayoutautor, adView, appbar, autorCheck, cardOptions, cardSecure,
          editpaa, hwidtext, inputlayouthwid, layoutAutor, layoutHwid, layoutMsg, main, mainView,
          msgCheck, passlauoy, passo, toolbarMain);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
