// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.core.widget.NestedScrollView;
import androidx.drawerlayout.widget.DrawerLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import androidx.viewpager.widget.ViewPager;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.navigation.NavigationView;
import com.google.android.material.progressindicator.LinearProgressIndicator;
import com.google.android.material.tabs.TabLayout;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainDrawerBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final AppBarLayout appBar;

  @NonNull
  public final NestedScrollView bottomSheet;

  @NonNull
  public final CoordinatorLayout coordinatorLayout;

  @NonNull
  public final DrawerLayout drawerLayoutMain;

  @NonNull
  public final NavigationView drawerNavigationView;

  @NonNull
  public final LinearProgressIndicator progressIndicator;

  @NonNull
  public final LinearLayout tab1;

  @NonNull
  public final LinearLayout tab2;

  @NonNull
  public final LinearLayout tab3;

  @NonNull
  public final LinearLayout tab4;

  @NonNull
  public final TabLayout tablayout;

  @NonNull
  public final Toolbar toolbarMain;

  @NonNull
  public final ViewPager viewpager;

  private ActivityMainDrawerBinding(@NonNull CoordinatorLayout rootView,
      @NonNull AppBarLayout appBar, @NonNull NestedScrollView bottomSheet,
      @NonNull CoordinatorLayout coordinatorLayout, @NonNull DrawerLayout drawerLayoutMain,
      @NonNull NavigationView drawerNavigationView,
      @NonNull LinearProgressIndicator progressIndicator, @NonNull LinearLayout tab1,
      @NonNull LinearLayout tab2, @NonNull LinearLayout tab3, @NonNull LinearLayout tab4,
      @NonNull TabLayout tablayout, @NonNull Toolbar toolbarMain, @NonNull ViewPager viewpager) {
    this.rootView = rootView;
    this.appBar = appBar;
    this.bottomSheet = bottomSheet;
    this.coordinatorLayout = coordinatorLayout;
    this.drawerLayoutMain = drawerLayoutMain;
    this.drawerNavigationView = drawerNavigationView;
    this.progressIndicator = progressIndicator;
    this.tab1 = tab1;
    this.tab2 = tab2;
    this.tab3 = tab3;
    this.tab4 = tab4;
    this.tablayout = tablayout;
    this.toolbarMain = toolbarMain;
    this.viewpager = viewpager;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainDrawerBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainDrawerBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main_drawer, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainDrawerBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.appBar;
      AppBarLayout appBar = ViewBindings.findChildViewById(rootView, id);
      if (appBar == null) {
        break missingId;
      }

      id = R.id.bottomSheet;
      NestedScrollView bottomSheet = ViewBindings.findChildViewById(rootView, id);
      if (bottomSheet == null) {
        break missingId;
      }

      CoordinatorLayout coordinatorLayout = (CoordinatorLayout) rootView;

      id = R.id.drawerLayoutMain;
      DrawerLayout drawerLayoutMain = ViewBindings.findChildViewById(rootView, id);
      if (drawerLayoutMain == null) {
        break missingId;
      }

      id = R.id.drawerNavigationView;
      NavigationView drawerNavigationView = ViewBindings.findChildViewById(rootView, id);
      if (drawerNavigationView == null) {
        break missingId;
      }

      id = R.id.progress_indicator;
      LinearProgressIndicator progressIndicator = ViewBindings.findChildViewById(rootView, id);
      if (progressIndicator == null) {
        break missingId;
      }

      id = R.id.tab1;
      LinearLayout tab1 = ViewBindings.findChildViewById(rootView, id);
      if (tab1 == null) {
        break missingId;
      }

      id = R.id.tab2;
      LinearLayout tab2 = ViewBindings.findChildViewById(rootView, id);
      if (tab2 == null) {
        break missingId;
      }

      id = R.id.tab3;
      LinearLayout tab3 = ViewBindings.findChildViewById(rootView, id);
      if (tab3 == null) {
        break missingId;
      }

      id = R.id.tab4;
      LinearLayout tab4 = ViewBindings.findChildViewById(rootView, id);
      if (tab4 == null) {
        break missingId;
      }

      id = R.id.tablayout;
      TabLayout tablayout = ViewBindings.findChildViewById(rootView, id);
      if (tablayout == null) {
        break missingId;
      }

      id = R.id.toolbar_main;
      Toolbar toolbarMain = ViewBindings.findChildViewById(rootView, id);
      if (toolbarMain == null) {
        break missingId;
      }

      id = R.id.viewpager;
      ViewPager viewpager = ViewBindings.findChildViewById(rootView, id);
      if (viewpager == null) {
        break missingId;
      }

      return new ActivityMainDrawerBinding((CoordinatorLayout) rootView, appBar, bottomSheet,
          coordinatorLayout, drawerLayoutMain, drawerNavigationView, progressIndicator, tab1, tab2,
          tab3, tab4, tablayout, toolbarMain, viewpager);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
