// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class DialogButtomResultSheetBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ConstraintLayout activityResult;

  @NonNull
  public final Button btnTestagain;

  @NonNull
  public final ConstraintLayout clConnectionName;

  @NonNull
  public final ConstraintLayout clDownload;

  @NonNull
  public final ConstraintLayout clPing;

  @NonNull
  public final ConstraintLayout clUpload;

  @NonNull
  public final TextView downloadUnit;

  @NonNull
  public final ImageView iconWifi;

  @NonNull
  public final ImageView ivDownloadResult;

  @NonNull
  public final ImageView ivPingResult;

  @NonNull
  public final ImageView ivUploadResult;

  @NonNull
  public final TextView tvConnectionInformation;

  @NonNull
  public final TextView tvDownloadResult;

  @NonNull
  public final TextView tvDownloadValue;

  @NonNull
  public final TextView tvPingResult;

  @NonNull
  public final TextView tvPingValue;

  @NonNull
  public final TextView tvUploadResult;

  @NonNull
  public final TextView tvUploadValue;

  @NonNull
  public final TextView uploadUnit;

  private DialogButtomResultSheetBinding(@NonNull ConstraintLayout rootView,
      @NonNull ConstraintLayout activityResult, @NonNull Button btnTestagain,
      @NonNull ConstraintLayout clConnectionName, @NonNull ConstraintLayout clDownload,
      @NonNull ConstraintLayout clPing, @NonNull ConstraintLayout clUpload,
      @NonNull TextView downloadUnit, @NonNull ImageView iconWifi,
      @NonNull ImageView ivDownloadResult, @NonNull ImageView ivPingResult,
      @NonNull ImageView ivUploadResult, @NonNull TextView tvConnectionInformation,
      @NonNull TextView tvDownloadResult, @NonNull TextView tvDownloadValue,
      @NonNull TextView tvPingResult, @NonNull TextView tvPingValue,
      @NonNull TextView tvUploadResult, @NonNull TextView tvUploadValue,
      @NonNull TextView uploadUnit) {
    this.rootView = rootView;
    this.activityResult = activityResult;
    this.btnTestagain = btnTestagain;
    this.clConnectionName = clConnectionName;
    this.clDownload = clDownload;
    this.clPing = clPing;
    this.clUpload = clUpload;
    this.downloadUnit = downloadUnit;
    this.iconWifi = iconWifi;
    this.ivDownloadResult = ivDownloadResult;
    this.ivPingResult = ivPingResult;
    this.ivUploadResult = ivUploadResult;
    this.tvConnectionInformation = tvConnectionInformation;
    this.tvDownloadResult = tvDownloadResult;
    this.tvDownloadValue = tvDownloadValue;
    this.tvPingResult = tvPingResult;
    this.tvPingValue = tvPingValue;
    this.tvUploadResult = tvUploadResult;
    this.tvUploadValue = tvUploadValue;
    this.uploadUnit = uploadUnit;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogButtomResultSheetBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogButtomResultSheetBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_buttom_result_sheet, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogButtomResultSheetBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      ConstraintLayout activityResult = (ConstraintLayout) rootView;

      id = R.id.btn_testagain;
      Button btnTestagain = ViewBindings.findChildViewById(rootView, id);
      if (btnTestagain == null) {
        break missingId;
      }

      id = R.id.cl_connection_name;
      ConstraintLayout clConnectionName = ViewBindings.findChildViewById(rootView, id);
      if (clConnectionName == null) {
        break missingId;
      }

      id = R.id.cl_download;
      ConstraintLayout clDownload = ViewBindings.findChildViewById(rootView, id);
      if (clDownload == null) {
        break missingId;
      }

      id = R.id.cl_ping;
      ConstraintLayout clPing = ViewBindings.findChildViewById(rootView, id);
      if (clPing == null) {
        break missingId;
      }

      id = R.id.cl_upload;
      ConstraintLayout clUpload = ViewBindings.findChildViewById(rootView, id);
      if (clUpload == null) {
        break missingId;
      }

      id = R.id.downloadUnit;
      TextView downloadUnit = ViewBindings.findChildViewById(rootView, id);
      if (downloadUnit == null) {
        break missingId;
      }

      id = R.id.icon_wifi;
      ImageView iconWifi = ViewBindings.findChildViewById(rootView, id);
      if (iconWifi == null) {
        break missingId;
      }

      id = R.id.iv_download_result;
      ImageView ivDownloadResult = ViewBindings.findChildViewById(rootView, id);
      if (ivDownloadResult == null) {
        break missingId;
      }

      id = R.id.iv_ping_result;
      ImageView ivPingResult = ViewBindings.findChildViewById(rootView, id);
      if (ivPingResult == null) {
        break missingId;
      }

      id = R.id.iv_upload_result;
      ImageView ivUploadResult = ViewBindings.findChildViewById(rootView, id);
      if (ivUploadResult == null) {
        break missingId;
      }

      id = R.id.tv_connection_information;
      TextView tvConnectionInformation = ViewBindings.findChildViewById(rootView, id);
      if (tvConnectionInformation == null) {
        break missingId;
      }

      id = R.id.tv_download_result;
      TextView tvDownloadResult = ViewBindings.findChildViewById(rootView, id);
      if (tvDownloadResult == null) {
        break missingId;
      }

      id = R.id.tv_download_value;
      TextView tvDownloadValue = ViewBindings.findChildViewById(rootView, id);
      if (tvDownloadValue == null) {
        break missingId;
      }

      id = R.id.tv_ping_result;
      TextView tvPingResult = ViewBindings.findChildViewById(rootView, id);
      if (tvPingResult == null) {
        break missingId;
      }

      id = R.id.tv_ping_value;
      TextView tvPingValue = ViewBindings.findChildViewById(rootView, id);
      if (tvPingValue == null) {
        break missingId;
      }

      id = R.id.tv_upload_result;
      TextView tvUploadResult = ViewBindings.findChildViewById(rootView, id);
      if (tvUploadResult == null) {
        break missingId;
      }

      id = R.id.tv_upload_value;
      TextView tvUploadValue = ViewBindings.findChildViewById(rootView, id);
      if (tvUploadValue == null) {
        break missingId;
      }

      id = R.id.uploadUnit;
      TextView uploadUnit = ViewBindings.findChildViewById(rootView, id);
      if (uploadUnit == null) {
        break missingId;
      }

      return new DialogButtomResultSheetBinding((ConstraintLayout) rootView, activityResult,
          btnTestagain, clConnectionName, clDownload, clPing, clUpload, downloadUnit, iconWifi,
          ivDownloadResult, ivPingResult, ivUploadResult, tvConnectionInformation, tvDownloadResult,
          tvDownloadValue, tvPingResult, tvPingValue, tvUploadResult, tvUploadValue, uploadUnit);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
