// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ListItemManagerBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageView ivManagerAdapterImageIcon;

  @NonNull
  public final LinearLayout ivManagerAdapterItemLayout;

  @NonNull
  public final LinearLayout listitemmanagerLinearLayout1;

  @NonNull
  public final TextView tvManagerAdapterFolderName;

  @NonNull
  public final TextView tvManagerAdapterFolderNameDate;

  private ListItemManagerBinding(@NonNull LinearLayout rootView,
      @NonNull ImageView ivManagerAdapterImageIcon,
      @NonNull LinearLayout ivManagerAdapterItemLayout,
      @NonNull LinearLayout listitemmanagerLinearLayout1,
      @NonNull TextView tvManagerAdapterFolderName,
      @NonNull TextView tvManagerAdapterFolderNameDate) {
    this.rootView = rootView;
    this.ivManagerAdapterImageIcon = ivManagerAdapterImageIcon;
    this.ivManagerAdapterItemLayout = ivManagerAdapterItemLayout;
    this.listitemmanagerLinearLayout1 = listitemmanagerLinearLayout1;
    this.tvManagerAdapterFolderName = tvManagerAdapterFolderName;
    this.tvManagerAdapterFolderNameDate = tvManagerAdapterFolderNameDate;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ListItemManagerBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ListItemManagerBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.list_item_manager, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ListItemManagerBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.ivManagerAdapter_ImageIcon;
      ImageView ivManagerAdapterImageIcon = ViewBindings.findChildViewById(rootView, id);
      if (ivManagerAdapterImageIcon == null) {
        break missingId;
      }

      LinearLayout ivManagerAdapterItemLayout = (LinearLayout) rootView;

      id = R.id.listitemmanagerLinearLayout1;
      LinearLayout listitemmanagerLinearLayout1 = ViewBindings.findChildViewById(rootView, id);
      if (listitemmanagerLinearLayout1 == null) {
        break missingId;
      }

      id = R.id.tvManagerAdapter_FolderName;
      TextView tvManagerAdapterFolderName = ViewBindings.findChildViewById(rootView, id);
      if (tvManagerAdapterFolderName == null) {
        break missingId;
      }

      id = R.id.tvManagerAdapter_FolderNameDate;
      TextView tvManagerAdapterFolderNameDate = ViewBindings.findChildViewById(rootView, id);
      if (tvManagerAdapterFolderNameDate == null) {
        break missingId;
      }

      return new ListItemManagerBinding((LinearLayout) rootView, ivManagerAdapterImageIcon,
          ivManagerAdapterItemLayout, listitemmanagerLinearLayout1, tvManagerAdapterFolderName,
          tvManagerAdapterFolderNameDate);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
