// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ListItemLogDrawerBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final LinearLayout listItemLogsLinearLayout;

  @NonNull
  public final TextView textLog;

  private ListItemLogDrawerBinding(@NonNull LinearLayout rootView,
      @NonNull LinearLayout listItemLogsLinearLayout, @NonNull TextView textLog) {
    this.rootView = rootView;
    this.listItemLogsLinearLayout = listItemLogsLinearLayout;
    this.textLog = textLog;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ListItemLogDrawerBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ListItemLogDrawerBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.list_item_log_drawer, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ListItemLogDrawerBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      LinearLayout listItemLogsLinearLayout = (LinearLayout) rootView;

      id = R.id.textLog;
      TextView textLog = ViewBindings.findChildViewById(rootView, id);
      if (textLog == null) {
        break missingId;
      }

      return new ListItemLogDrawerBinding((LinearLayout) rootView, listItemLogsLinearLayout,
          textLog);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
