// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class MasInfoBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final TextView aboutDesc1;

  @NonNull
  public final TextView aboutDesc2;

  @NonNull
  public final TextView aboutDesc2t;

  @NonNull
  public final CardView cardViewAbout;

  @NonNull
  public final CardView helpAbout;

  @NonNull
  public final TextView helpTitle2;

  private MasInfoBinding(@NonNull ScrollView rootView, @NonNull TextView aboutDesc1,
      @NonNull TextView aboutDesc2, @NonNull TextView aboutDesc2t, @NonNull CardView cardViewAbout,
      @NonNull CardView helpAbout, @NonNull TextView helpTitle2) {
    this.rootView = rootView;
    this.aboutDesc1 = aboutDesc1;
    this.aboutDesc2 = aboutDesc2;
    this.aboutDesc2t = aboutDesc2t;
    this.cardViewAbout = cardViewAbout;
    this.helpAbout = helpAbout;
    this.helpTitle2 = helpTitle2;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static MasInfoBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static MasInfoBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.mas_info, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static MasInfoBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.about_desc_1;
      TextView aboutDesc1 = ViewBindings.findChildViewById(rootView, id);
      if (aboutDesc1 == null) {
        break missingId;
      }

      id = R.id.about_desc_2;
      TextView aboutDesc2 = ViewBindings.findChildViewById(rootView, id);
      if (aboutDesc2 == null) {
        break missingId;
      }

      id = R.id.about_desc_2t;
      TextView aboutDesc2t = ViewBindings.findChildViewById(rootView, id);
      if (aboutDesc2t == null) {
        break missingId;
      }

      id = R.id.card_view_about;
      CardView cardViewAbout = ViewBindings.findChildViewById(rootView, id);
      if (cardViewAbout == null) {
        break missingId;
      }

      id = R.id.help_about;
      CardView helpAbout = ViewBindings.findChildViewById(rootView, id);
      if (helpAbout == null) {
        break missingId;
      }

      id = R.id.help_title_2;
      TextView helpTitle2 = ViewBindings.findChildViewById(rootView, id);
      if (helpTitle2 == null) {
        break missingId;
      }

      return new MasInfoBinding((ScrollView) rootView, aboutDesc1, aboutDesc2, aboutDesc2t,
          cardViewAbout, helpAbout, helpTitle2);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
