// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class MoreViewBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView behaviorIcon;

  @NonNull
  public final ConstraintLayout expor;

  @NonNull
  public final ImageView img;

  @NonNull
  public final ImageView imgDelete;

  @NonNull
  public final ConstraintLayout save;

  private MoreViewBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView behaviorIcon,
      @NonNull ConstraintLayout expor, @NonNull ImageView img, @NonNull ImageView imgDelete,
      @NonNull ConstraintLayout save) {
    this.rootView = rootView;
    this.behaviorIcon = behaviorIcon;
    this.expor = expor;
    this.img = img;
    this.imgDelete = imgDelete;
    this.save = save;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static MoreViewBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static MoreViewBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.more_view, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static MoreViewBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.behavior_icon;
      ImageView behaviorIcon = ViewBindings.findChildViewById(rootView, id);
      if (behaviorIcon == null) {
        break missingId;
      }

      id = R.id.expor;
      ConstraintLayout expor = ViewBindings.findChildViewById(rootView, id);
      if (expor == null) {
        break missingId;
      }

      id = R.id.img;
      ImageView img = ViewBindings.findChildViewById(rootView, id);
      if (img == null) {
        break missingId;
      }

      id = R.id.imgDelete;
      ImageView imgDelete = ViewBindings.findChildViewById(rootView, id);
      if (imgDelete == null) {
        break missingId;
      }

      id = R.id.save;
      ConstraintLayout save = ViewBindings.findChildViewById(rootView, id);
      if (save == null) {
        break missingId;
      }

      return new MoreViewBinding((ConstraintLayout) rootView, behaviorIcon, expor, img, imgDelete,
          save);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
