// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class NavHeaderBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView navHeaderAppName;

  @NonNull
  public final TextView navHeaderAppVersion;

  @NonNull
  public final ImageView navHeaderCircleimageviewId;

  private NavHeaderBinding(@NonNull LinearLayout rootView, @NonNull TextView navHeaderAppName,
      @NonNull TextView navHeaderAppVersion, @NonNull ImageView navHeaderCircleimageviewId) {
    this.rootView = rootView;
    this.navHeaderAppName = navHeaderAppName;
    this.navHeaderAppVersion = navHeaderAppVersion;
    this.navHeaderCircleimageviewId = navHeaderCircleimageviewId;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static NavHeaderBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static NavHeaderBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.nav_header, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static NavHeaderBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.nav_header_app_name;
      TextView navHeaderAppName = ViewBindings.findChildViewById(rootView, id);
      if (navHeaderAppName == null) {
        break missingId;
      }

      id = R.id.nav_headerAppVersion;
      TextView navHeaderAppVersion = ViewBindings.findChildViewById(rootView, id);
      if (navHeaderAppVersion == null) {
        break missingId;
      }

      id = R.id.nav_header_circleimageview_id;
      ImageView navHeaderCircleimageviewId = ViewBindings.findChildViewById(rootView, id);
      if (navHeaderCircleimageviewId == null) {
        break missingId;
      }

      return new NavHeaderBinding((LinearLayout) rootView, navHeaderAppName, navHeaderAppVersion,
          navHeaderCircleimageviewId);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
