// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.ScrollView;
import android.widget.Spinner;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class PayloadGeneratorDialogBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final CheckBox cbBack;

  @NonNull
  public final CheckBox cbDual;

  @NonNull
  public final CheckBox cbForward;

  @NonNull
  public final CheckBox cbFront;

  @NonNull
  public final CheckBox cbKeep;

  @NonNull
  public final CheckBox cbOnline;

  @NonNull
  public final CheckBox cbRaw;

  @NonNull
  public final CheckBox cbReferer;

  @NonNull
  public final CheckBox cbReverse;

  @NonNull
  public final CheckBox cbRotate;

  @NonNull
  public final CheckBox cbUser;

  @NonNull
  public final TextInputLayout editTextHint;

  @NonNull
  public final TextInputEditText host;

  @NonNull
  public final Spinner injectSpin;

  @NonNull
  public final LinearLayout payloadGeneratorDialogLinearLayout;

  @NonNull
  public final RadioButton rDirect;

  @NonNull
  public final RadioButton rNormal;

  @NonNull
  public final RadioButton rSplit;

  @NonNull
  public final Spinner requestSpin;

  @NonNull
  public final Spinner splitSpin;

  private PayloadGeneratorDialogBinding(@NonNull ScrollView rootView, @NonNull CheckBox cbBack,
      @NonNull CheckBox cbDual, @NonNull CheckBox cbForward, @NonNull CheckBox cbFront,
      @NonNull CheckBox cbKeep, @NonNull CheckBox cbOnline, @NonNull CheckBox cbRaw,
      @NonNull CheckBox cbReferer, @NonNull CheckBox cbReverse, @NonNull CheckBox cbRotate,
      @NonNull CheckBox cbUser, @NonNull TextInputLayout editTextHint,
      @NonNull TextInputEditText host, @NonNull Spinner injectSpin,
      @NonNull LinearLayout payloadGeneratorDialogLinearLayout, @NonNull RadioButton rDirect,
      @NonNull RadioButton rNormal, @NonNull RadioButton rSplit, @NonNull Spinner requestSpin,
      @NonNull Spinner splitSpin) {
    this.rootView = rootView;
    this.cbBack = cbBack;
    this.cbDual = cbDual;
    this.cbForward = cbForward;
    this.cbFront = cbFront;
    this.cbKeep = cbKeep;
    this.cbOnline = cbOnline;
    this.cbRaw = cbRaw;
    this.cbReferer = cbReferer;
    this.cbReverse = cbReverse;
    this.cbRotate = cbRotate;
    this.cbUser = cbUser;
    this.editTextHint = editTextHint;
    this.host = host;
    this.injectSpin = injectSpin;
    this.payloadGeneratorDialogLinearLayout = payloadGeneratorDialogLinearLayout;
    this.rDirect = rDirect;
    this.rNormal = rNormal;
    this.rSplit = rSplit;
    this.requestSpin = requestSpin;
    this.splitSpin = splitSpin;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static PayloadGeneratorDialogBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static PayloadGeneratorDialogBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.payload_generator_dialog, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static PayloadGeneratorDialogBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cbBack;
      CheckBox cbBack = ViewBindings.findChildViewById(rootView, id);
      if (cbBack == null) {
        break missingId;
      }

      id = R.id.cbDual;
      CheckBox cbDual = ViewBindings.findChildViewById(rootView, id);
      if (cbDual == null) {
        break missingId;
      }

      id = R.id.cbForward;
      CheckBox cbForward = ViewBindings.findChildViewById(rootView, id);
      if (cbForward == null) {
        break missingId;
      }

      id = R.id.cbFront;
      CheckBox cbFront = ViewBindings.findChildViewById(rootView, id);
      if (cbFront == null) {
        break missingId;
      }

      id = R.id.cbKeep;
      CheckBox cbKeep = ViewBindings.findChildViewById(rootView, id);
      if (cbKeep == null) {
        break missingId;
      }

      id = R.id.cbOnline;
      CheckBox cbOnline = ViewBindings.findChildViewById(rootView, id);
      if (cbOnline == null) {
        break missingId;
      }

      id = R.id.cbRaw;
      CheckBox cbRaw = ViewBindings.findChildViewById(rootView, id);
      if (cbRaw == null) {
        break missingId;
      }

      id = R.id.cbReferer;
      CheckBox cbReferer = ViewBindings.findChildViewById(rootView, id);
      if (cbReferer == null) {
        break missingId;
      }

      id = R.id.cbReverse;
      CheckBox cbReverse = ViewBindings.findChildViewById(rootView, id);
      if (cbReverse == null) {
        break missingId;
      }

      id = R.id.cbRotate;
      CheckBox cbRotate = ViewBindings.findChildViewById(rootView, id);
      if (cbRotate == null) {
        break missingId;
      }

      id = R.id.cbUser;
      CheckBox cbUser = ViewBindings.findChildViewById(rootView, id);
      if (cbUser == null) {
        break missingId;
      }

      id = R.id.editTextHint;
      TextInputLayout editTextHint = ViewBindings.findChildViewById(rootView, id);
      if (editTextHint == null) {
        break missingId;
      }

      id = R.id.host;
      TextInputEditText host = ViewBindings.findChildViewById(rootView, id);
      if (host == null) {
        break missingId;
      }

      id = R.id.inject_spin;
      Spinner injectSpin = ViewBindings.findChildViewById(rootView, id);
      if (injectSpin == null) {
        break missingId;
      }

      id = R.id.payload_generator_dialogLinearLayout;
      LinearLayout payloadGeneratorDialogLinearLayout = ViewBindings.findChildViewById(rootView, id);
      if (payloadGeneratorDialogLinearLayout == null) {
        break missingId;
      }

      id = R.id.rDirect;
      RadioButton rDirect = ViewBindings.findChildViewById(rootView, id);
      if (rDirect == null) {
        break missingId;
      }

      id = R.id.rNormal;
      RadioButton rNormal = ViewBindings.findChildViewById(rootView, id);
      if (rNormal == null) {
        break missingId;
      }

      id = R.id.rSplit;
      RadioButton rSplit = ViewBindings.findChildViewById(rootView, id);
      if (rSplit == null) {
        break missingId;
      }

      id = R.id.request_spin;
      Spinner requestSpin = ViewBindings.findChildViewById(rootView, id);
      if (requestSpin == null) {
        break missingId;
      }

      id = R.id.split_spin;
      Spinner splitSpin = ViewBindings.findChildViewById(rootView, id);
      if (splitSpin == null) {
        break missingId;
      }

      return new PayloadGeneratorDialogBinding((ScrollView) rootView, cbBack, cbDual, cbForward,
          cbFront, cbKeep, cbOnline, cbRaw, cbReferer, cbReverse, cbRotate, cbUser, editTextHint,
          host, injectSpin, payloadGeneratorDialogLinearLayout, rDirect, rNormal, rSplit,
          requestSpin, splitSpin);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
