// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.gms.ads.AdView;
import com.google.android.material.materialswitch.MaterialSwitch;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ProxySettingsBinding implements ViewBinding {
  @NonNull
  private final CardView rootView;

  @NonNull
  public final AdView adView5;

  @NonNull
  public final Button btnCopyDetails;

  @NonNull
  public final MaterialSwitch cbHotspot;

  @NonNull
  public final MaterialSwitch cbProxy;

  @NonNull
  public final TextView ipLayout;

  @NonNull
  public final LinearLayout ipLayoutContainer;

  @NonNull
  public final TextView textport;

  @NonNull
  public final Toolbar toolbarMain;

  @NonNull
  public final TextView tvHotspotInfo;

  @NonNull
  public final TextView tvInfo;

  private ProxySettingsBinding(@NonNull CardView rootView, @NonNull AdView adView5,
      @NonNull Button btnCopyDetails, @NonNull MaterialSwitch cbHotspot,
      @NonNull MaterialSwitch cbProxy, @NonNull TextView ipLayout,
      @NonNull LinearLayout ipLayoutContainer, @NonNull TextView textport,
      @NonNull Toolbar toolbarMain, @NonNull TextView tvHotspotInfo, @NonNull TextView tvInfo) {
    this.rootView = rootView;
    this.adView5 = adView5;
    this.btnCopyDetails = btnCopyDetails;
    this.cbHotspot = cbHotspot;
    this.cbProxy = cbProxy;
    this.ipLayout = ipLayout;
    this.ipLayoutContainer = ipLayoutContainer;
    this.textport = textport;
    this.toolbarMain = toolbarMain;
    this.tvHotspotInfo = tvHotspotInfo;
    this.tvInfo = tvInfo;
  }

  @Override
  @NonNull
  public CardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ProxySettingsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ProxySettingsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.proxy_settings, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ProxySettingsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.adView5;
      AdView adView5 = ViewBindings.findChildViewById(rootView, id);
      if (adView5 == null) {
        break missingId;
      }

      id = R.id.btn_copy_details;
      Button btnCopyDetails = ViewBindings.findChildViewById(rootView, id);
      if (btnCopyDetails == null) {
        break missingId;
      }

      id = R.id.cb_hotspot;
      MaterialSwitch cbHotspot = ViewBindings.findChildViewById(rootView, id);
      if (cbHotspot == null) {
        break missingId;
      }

      id = R.id.cb_proxy;
      MaterialSwitch cbProxy = ViewBindings.findChildViewById(rootView, id);
      if (cbProxy == null) {
        break missingId;
      }

      id = R.id.ip_layout;
      TextView ipLayout = ViewBindings.findChildViewById(rootView, id);
      if (ipLayout == null) {
        break missingId;
      }

      id = R.id.ip_layout_container;
      LinearLayout ipLayoutContainer = ViewBindings.findChildViewById(rootView, id);
      if (ipLayoutContainer == null) {
        break missingId;
      }

      id = R.id.textport;
      TextView textport = ViewBindings.findChildViewById(rootView, id);
      if (textport == null) {
        break missingId;
      }

      id = R.id.toolbar_main;
      Toolbar toolbarMain = ViewBindings.findChildViewById(rootView, id);
      if (toolbarMain == null) {
        break missingId;
      }

      id = R.id.tv_hotspot_info;
      TextView tvHotspotInfo = ViewBindings.findChildViewById(rootView, id);
      if (tvHotspotInfo == null) {
        break missingId;
      }

      id = R.id.tv_info;
      TextView tvInfo = ViewBindings.findChildViewById(rootView, id);
      if (tvInfo == null) {
        break missingId;
      }

      return new ProxySettingsBinding((CardView) rootView, adView5, btnCopyDetails, cbHotspot,
          cbProxy, ipLayout, ipLayoutContainer, textport, toolbarMain, tvHotspotInfo, tvInfo);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
