// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.AppCompatButton;
import androidx.appcompat.widget.Toolbar;
import androidx.cardview.widget.CardView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class TunnelTypeBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final RadioButton btnDirect;

  @NonNull
  public final RadioButton btnHTTP;

  @NonNull
  public final RadioButton btnSSL;

  @NonNull
  public final RadioButton btnSlowDNS;

  @NonNull
  public final RadioButton btnSslPayload;

  @NonNull
  public final RadioButton btnSslrp;

  @NonNull
  public final RadioButton btnTYPE;

  @NonNull
  public final RadioButton btnUDP;

  @NonNull
  public final RadioButton btnV2RAY;

  @NonNull
  public final LinearLayout controlMenuLayoutRow0;

  @NonNull
  public final CheckBox customPayload;

  @NonNull
  public final LinearLayout loadTunnel;

  @NonNull
  public final AppCompatButton saveButton;

  @NonNull
  public final Toolbar toolbarMain;

  @NonNull
  public final CardView tunnel;

  @NonNull
  public final CardView tunnel1;

  @NonNull
  public final CardView tunnel2;

  @NonNull
  public final CardView tunnel3;

  @NonNull
  public final RelativeLayout tunnelTypeLayout;

  @NonNull
  public final TextView tunnelTypeTitle;

  @NonNull
  public final TextView tunneltypeTextView1;

  private TunnelTypeBinding(@NonNull LinearLayout rootView, @NonNull RadioButton btnDirect,
      @NonNull RadioButton btnHTTP, @NonNull RadioButton btnSSL, @NonNull RadioButton btnSlowDNS,
      @NonNull RadioButton btnSslPayload, @NonNull RadioButton btnSslrp,
      @NonNull RadioButton btnTYPE, @NonNull RadioButton btnUDP, @NonNull RadioButton btnV2RAY,
      @NonNull LinearLayout controlMenuLayoutRow0, @NonNull CheckBox customPayload,
      @NonNull LinearLayout loadTunnel, @NonNull AppCompatButton saveButton,
      @NonNull Toolbar toolbarMain, @NonNull CardView tunnel, @NonNull CardView tunnel1,
      @NonNull CardView tunnel2, @NonNull CardView tunnel3,
      @NonNull RelativeLayout tunnelTypeLayout, @NonNull TextView tunnelTypeTitle,
      @NonNull TextView tunneltypeTextView1) {
    this.rootView = rootView;
    this.btnDirect = btnDirect;
    this.btnHTTP = btnHTTP;
    this.btnSSL = btnSSL;
    this.btnSlowDNS = btnSlowDNS;
    this.btnSslPayload = btnSslPayload;
    this.btnSslrp = btnSslrp;
    this.btnTYPE = btnTYPE;
    this.btnUDP = btnUDP;
    this.btnV2RAY = btnV2RAY;
    this.controlMenuLayoutRow0 = controlMenuLayoutRow0;
    this.customPayload = customPayload;
    this.loadTunnel = loadTunnel;
    this.saveButton = saveButton;
    this.toolbarMain = toolbarMain;
    this.tunnel = tunnel;
    this.tunnel1 = tunnel1;
    this.tunnel2 = tunnel2;
    this.tunnel3 = tunnel3;
    this.tunnelTypeLayout = tunnelTypeLayout;
    this.tunnelTypeTitle = tunnelTypeTitle;
    this.tunneltypeTextView1 = tunneltypeTextView1;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static TunnelTypeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static TunnelTypeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.tunnel_type, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static TunnelTypeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnDirect;
      RadioButton btnDirect = ViewBindings.findChildViewById(rootView, id);
      if (btnDirect == null) {
        break missingId;
      }

      id = R.id.btnHTTP;
      RadioButton btnHTTP = ViewBindings.findChildViewById(rootView, id);
      if (btnHTTP == null) {
        break missingId;
      }

      id = R.id.btnSSL;
      RadioButton btnSSL = ViewBindings.findChildViewById(rootView, id);
      if (btnSSL == null) {
        break missingId;
      }

      id = R.id.btnSlowDNS;
      RadioButton btnSlowDNS = ViewBindings.findChildViewById(rootView, id);
      if (btnSlowDNS == null) {
        break missingId;
      }

      id = R.id.btnSslPayload;
      RadioButton btnSslPayload = ViewBindings.findChildViewById(rootView, id);
      if (btnSslPayload == null) {
        break missingId;
      }

      id = R.id.btnSslrp;
      RadioButton btnSslrp = ViewBindings.findChildViewById(rootView, id);
      if (btnSslrp == null) {
        break missingId;
      }

      id = R.id.btnTYPE;
      RadioButton btnTYPE = ViewBindings.findChildViewById(rootView, id);
      if (btnTYPE == null) {
        break missingId;
      }

      id = R.id.btnUDP;
      RadioButton btnUDP = ViewBindings.findChildViewById(rootView, id);
      if (btnUDP == null) {
        break missingId;
      }

      id = R.id.btnV2RAY;
      RadioButton btnV2RAY = ViewBindings.findChildViewById(rootView, id);
      if (btnV2RAY == null) {
        break missingId;
      }

      id = R.id.controlMenuLayoutRow0;
      LinearLayout controlMenuLayoutRow0 = ViewBindings.findChildViewById(rootView, id);
      if (controlMenuLayoutRow0 == null) {
        break missingId;
      }

      id = R.id.customPayload;
      CheckBox customPayload = ViewBindings.findChildViewById(rootView, id);
      if (customPayload == null) {
        break missingId;
      }

      id = R.id.load_tunnel;
      LinearLayout loadTunnel = ViewBindings.findChildViewById(rootView, id);
      if (loadTunnel == null) {
        break missingId;
      }

      id = R.id.saveButton;
      AppCompatButton saveButton = ViewBindings.findChildViewById(rootView, id);
      if (saveButton == null) {
        break missingId;
      }

      id = R.id.toolbar_main;
      Toolbar toolbarMain = ViewBindings.findChildViewById(rootView, id);
      if (toolbarMain == null) {
        break missingId;
      }

      id = R.id.tunnel;
      CardView tunnel = ViewBindings.findChildViewById(rootView, id);
      if (tunnel == null) {
        break missingId;
      }

      id = R.id.tunnel_;
      CardView tunnel1 = ViewBindings.findChildViewById(rootView, id);
      if (tunnel1 == null) {
        break missingId;
      }

      id = R.id.tunnel___;
      CardView tunnel2 = ViewBindings.findChildViewById(rootView, id);
      if (tunnel2 == null) {
        break missingId;
      }

      id = R.id.tunnel__;
      CardView tunnel3 = ViewBindings.findChildViewById(rootView, id);
      if (tunnel3 == null) {
        break missingId;
      }

      id = R.id.tunnelTypeLayout;
      RelativeLayout tunnelTypeLayout = ViewBindings.findChildViewById(rootView, id);
      if (tunnelTypeLayout == null) {
        break missingId;
      }

      id = R.id.tunnelTypeTitle;
      TextView tunnelTypeTitle = ViewBindings.findChildViewById(rootView, id);
      if (tunnelTypeTitle == null) {
        break missingId;
      }

      id = R.id.tunneltypeTextView1;
      TextView tunneltypeTextView1 = ViewBindings.findChildViewById(rootView, id);
      if (tunneltypeTextView1 == null) {
        break missingId;
      }

      return new TunnelTypeBinding((LinearLayout) rootView, btnDirect, btnHTTP, btnSSL, btnSlowDNS,
          btnSslPayload, btnSslrp, btnTYPE, btnUDP, btnV2RAY, controlMenuLayoutRow0, customPayload,
          loadTunnel, saveButton, toolbarMain, tunnel, tunnel1, tunnel2, tunnel3, tunnelTypeLayout,
          tunnelTypeTitle, tunneltypeTextView1);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
