// Generated by view binder compiler. Do not edit!
package com.jepongdevxyz.vpn.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.textfield.TextInputEditText;
import com.jepongdevxyz.vpn.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class UdpBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextInputEditText auth;

  @NonNull
  public final TextInputEditText buffer;

  @NonNull
  public final TextInputEditText obfs;

  @NonNull
  public final TextInputEditText server;

  @NonNull
  public final TextInputEditText udpdown;

  @NonNull
  public final TextInputEditText udpup;

  private UdpBinding(@NonNull LinearLayout rootView, @NonNull TextInputEditText auth,
      @NonNull TextInputEditText buffer, @NonNull TextInputEditText obfs,
      @NonNull TextInputEditText server, @NonNull TextInputEditText udpdown,
      @NonNull TextInputEditText udpup) {
    this.rootView = rootView;
    this.auth = auth;
    this.buffer = buffer;
    this.obfs = obfs;
    this.server = server;
    this.udpdown = udpdown;
    this.udpup = udpup;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static UdpBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static UdpBinding inflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup parent,
      boolean attachToParent) {
    View root = inflater.inflate(R.layout.udp, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static UdpBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.auth;
      TextInputEditText auth = ViewBindings.findChildViewById(rootView, id);
      if (auth == null) {
        break missingId;
      }

      id = R.id.buffer;
      TextInputEditText buffer = ViewBindings.findChildViewById(rootView, id);
      if (buffer == null) {
        break missingId;
      }

      id = R.id.obfs;
      TextInputEditText obfs = ViewBindings.findChildViewById(rootView, id);
      if (obfs == null) {
        break missingId;
      }

      id = R.id.server;
      TextInputEditText server = ViewBindings.findChildViewById(rootView, id);
      if (server == null) {
        break missingId;
      }

      id = R.id.udpdown;
      TextInputEditText udpdown = ViewBindings.findChildViewById(rootView, id);
      if (udpdown == null) {
        break missingId;
      }

      id = R.id.udpup;
      TextInputEditText udpup = ViewBindings.findChildViewById(rootView, id);
      if (udpup == null) {
        break missingId;
      }

      return new UdpBinding((LinearLayout) rootView, auth, buffer, obfs, server, udpdown, udpup);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
